### ISSUE TITLE
Compatible Dapp List

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/hello#16]
Hey developers!  We're building up a list of the best MetaMask-compatible dapps we can find, so if you've got one to share, please post it here!

**Comment by SilentCicero** [comment]
weifund.surge.sh -- boardroom to come soon =D

**Comment by jorisbontje** [comment]
http://makerdao.github.io/maker-otc/

**Comment by flyswatter** [comment]
http://vote.daohub.org/

**Comment by flyswatter** [comment]
Token Factory (pending link from @simondlr)

**Comment by flyswatter** [comment]
[Benefactory](http://sorryring.surge.sh/)!!!!

**Comment by kumavis** [comment]
Haven't evaluated yet but got request via email:
```
Here is a very simple DApp that sends emails from Ethereum: http://blockchain2email.com/
```

**Comment by etherdelta** [comment]
EtherDelta (https://etherdelta.github.io), the decentralized Ethereum token exchange, supports MetaMask!

**Comment by flyswatter** [comment]
Well that was fast!!  Awesome work, @etherdelta!

I'd like to also recommend a feature that makes for an even better experience for MetaMask users: Checking the network (morden vs main-net), and conditionally loading the appropriate contract.

This makes it easy for users to dabble on your site with fake tokens, before diving in to trust it with real tokens.

We've got a section on this feature in our compatibility guide:
https://github.com/MetaMask/faq#network-check

**Comment by etherdelta** [comment]
Good idea! Adding that to my list.

**Comment by sridhar87** [comment]
etherfaces.com - We have enabled metamask on our website. Please checkout and let us know. Also, I'm having an issue using Metamask - for the first transaction - I'm able to see the transaction value and fee properly. From the second transaction onwards, my fee is set to a high 50 million, and it is unlikely that transaction would be successful. This happened to me twice. Let us know if this is a known bug.
Thanks,
Sridhar

**Comment by kumavis** [comment]
@sridhar87 thanks - you can follow the issue here https://github.com/MetaMask/hello/issues/16

**Comment by viknovak** [comment]
Hi MetaMask team,

big fan of MetaMask here - it's a great tool to actually make DApps accessible to many users. Thanks!

I recently saw that you have a list of 'supported dapps' on your website.  I run ethereumlottery.io and actually specifically develop with MetaMask in mind. So I would like to submit my DApp for consideration:

  Icon: ![ethereumlottery](https://user-images.githubusercontent.com/18382197/31375461-ee59d0ae-ada1-11e7-8e38-c0a3ba5ff893.png) (70x70 png)

  Link: http://ethereumlottery.io

I hope that it can be included. Thank you!

PS: I first tried sending an email to the address listed on your website. But I got back an error:

```
<dapps@metamask.io>: host mxb.mailgun.org[52.202.23.146] said: 550 5.1.0
Recipient rejected: <dapps@metamask.io> (in reply to RCPT TO command)
```

**Comment by jorisbontje** [comment]
We have tagged all DApps that claim metamask support from above and other internal lists with `metamask` on State of the DApps, https://www.stateofthedapps.com 
This will cause a cute fox badge to appear 🦊 

![screenshot 2017-10-25 22 54 57](https://user-images.githubusercontent.com/620959/32022744-a3e45566-b9d7-11e7-998c-7b9f74174380.png)

Do send a change request if anything is incorrect!

**Comment by kumavis** [comment]
@jorisbontje thats awesome! can we embed https://www.stateofthedapps.com in an iframe with a filter to only show metamask-supported dapps?

**Comment by danfinlay** [comment]
We are now using  https://www.stateofthedapps.com  as our dapp list, so we can close this!
