### ISSUE TITLE
eth_getAccounts give back an empty Array when the vault is locked

### ISSUE THREAD

**Issue by wighawag** [MetaMask/hello#18]
When the vault is locked calling eth_getAccounts give back an empty array.
When I first hit this, I thought about detecting if metamask is the current provider in order to ask the user to unlock its vault. 
But maybe instead of giving back an empty array, metamask provider could return an error indicating that the vault is locked. This way the dapp can explain it to the user

**Comment by kumavis** [comment]
Confirmed as an issue

**Comment by kumavis** [comment]
So we still return an empty array but if you attempt to submit a tx like this it will bring up a notification. closing for now, will revisit if this is insufficiently clear.
