### ISSUE TITLE
no callback called upon user rejecting tx

### ISSUE THREAD

**Issue by wighawag** [MetaMask/hello#20]
Since some time now, metamask is not calling back upon the user rejecting the tx.
Accepting is fine but rejecting no.

```js
contract.method.sendTransaction(options,function(err,txHash) {
  // this never get called upon user rejecting but get called upon the user accepting the tx
});
```

**Comment by wighawag** [comment]
The issue is still present  in 2.6.1

**Comment by flyswatter** [comment]
When you first submitted, I was able to reproduce, and fixed it locally for myself, and considered it resolved.

As of 2.6.1, I've been unable to replicate this issue. When I try with a simple project, rejecting the tx sends an error in the callback to the UI, specifying the user rejected the transaction, like I think it should.

Could you provide some sample code to reproduce this?

**Comment by wighawag** [comment]
I have only my current project so far but puting breakpoints I can see that it call this
```
contractInstance.start.sendTransaction(blockNumber,1,version,option,function(err,txHash) {
// but never reach there
});
```

when converted to json, option is :
```json
{
"from":"0xf78cd306b23031de9e739a5bcde61764e82ad5ef",
"gas":800000,
"gasPrice":"24817635022",
"value":"100000000000000000"
}
```

I am not in position right now to simplify it, I will at some point release an alpha version of my project. It might be sufficient for you? if you cannot reproduce it in the mean time

**Comment by flyswatter** [comment]
Cool, I'll do what I can with this in the meanwhile, I'm sure we'll find it sooner or later.

- Dan

**Comment by wighawag** [comment]
I cannot reproduce the issue anymore. Might have been fixed in a newer version?
