### ISSUE TITLE
Fix mystery crashes

### ISSUE THREAD

**Issue by ConsentDevelopment** [MetaMask/hello#24]
I am using the plugin a lot for deployment testing but it is very unstable and so it is always crashing.

System OS - windows 10 64bit

**Comment by flyswatter** [comment]
Hi, sorry to hear MetaMask has been unstable for you. In all honesty, our team is mostly on macs & linux, so it's possible we've overlooked something for Windows.

I'll spend some time using MetaMask on windows soon, and debug any crashes I see. Are there any specific tips or Dapps you can suggest for reproducing your crashes?

**Comment by ConsentDevelopment** [comment]
Hard to reproduce the crashing.  It seems to crash the most while idle.  I am working with a very large sol file which contains 2 libraries and a contract so that may contribute to the crashing.

**Comment by flyswatter** [comment]
Does it make a lot of heavyweight requests of the blockchain while idle?

- Dan

**Comment by zoernert** [comment]
I might have an issue that is related to this. But MetaMask is not crashing... instead it is providing "incorrect" values for call requests. At the moment I have although some challenges getting my transaction through on the public network. If it helps I could deploy my DAPP to a public address (it will be as soon as development is finished).

**Comment by flyswatter** [comment]
I think that's actually a different issue, related to our backend provider.

The problem is caused when one of our Ethereum nodes falls out of sync and the load balancer passes you between synced and unsynced nodes.

The Infura team is adding some infrastructure to prevent that in the future, but in the meanwhile the sure way to fix that would be to point MetaMask at a local Ethereum RPC.

- Dan

**Comment by ConsentDevelopment** [comment]
No, while idle there is nothing happening transaction wise.

**Comment by kumavis** [comment]
http://stackoverflow.com/questions/12219058/how-to-debug-a-chrome-browser-extension-which-is-crashing

**Comment by kumavis** [comment]
just got bit again 💀

**Comment by ConsentDevelopment** [comment]
I should mention that the crashes happen when I am using the solidity-browser in conjunction with Metamask for contract deployment to the blockchain.  Using Injected Web3 provided by Metamask.

**Comment by flyswatter** [comment]
Oh, [browser-solidity](https://ethereum.github.io/browser-solidity/)?  That's a good lead!  Any other leads will always help, like specific actions, but this is still better!

**Comment by wighawag** [comment]
Here some more doc to watch crash log with chrome : https://www.chromium.org/for-testers/enable-logging, 
It mentions a nice tool for windows to watch log in real time : https://github.com/google/sawbuck

**Comment by flyswatter** [comment]
That’s a great doc, thanks you!!
