### ISSUE TITLE
Add "Spend All" button

### ISSUE THREAD

**Issue by mcgravier** [MetaMask/hello#25]
In order for easy movement of funds to another wallet, MetaMask should have option to spend all funds with one click button. 

It is hard to manually estimate how much needs to be sent in order to leave enough ETH to cover transaction fee

**Comment by flyswatter** [comment]
Totally agree, Mist does this great, surprised this wasn't an issue yet!

- Dan

**Comment by Zanibas** [comment]
Being handled in https://github.com/MetaMask/metamask-plugin/issues/1537
