### ISSUE TITLE
redux devtool throwing errors

### ISSUE THREAD

**Issue by vincentserpoul** [MetaMask/hello#27]
Hi,

I've been using metamask for a small project using react and redux.
I'm using redux-dev-tools and it throws errors :
inpage-provider.js:84Uncaught Error: The MetaMask Web3 object does not support synchronous methods. See https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#all-async---think-of-metamask-as-a-light-client for details.

I'm not sure if it is in anyway fixable on your side, but it took me quite some time to understand what was throwing errors, so it's worth mentioning for other people!

**Comment by flyswatter** [comment]
Was this error not thrown in response to the use of a synchronous web3 method?

If not, could you do a stack trace and find what part of react or redux is triggering this code path?

This error is deliberately thrown when apps attempt to use synchronous web3 methods, so I'm inclined to think our error system correctly informed you of the issue that prevented MetaMask from working with your app, and how to make your app MetaMask compatible.

**Comment by flyswatter** [comment]
You made this error more descriptive, so I'm closing this.  Thanks!

**Comment by flyswatter** [comment]
Sure.

**Comment by flyswatter** [comment]
Did you get to try it out?

**Comment by vincentserpoul** [comment]
yes, it says:

The MetaMask Web3 object does not support synchronous methods like **eth_mining**

I'm not using that method in my codebase at all, so something is triggering it.

**Comment by flyswatter** [comment]
Could you trace the stack to where it's being called, or give us the code to try running ourselves?

- Dan

**Comment by vincentserpoul** [comment]
I got the stack trace, but it's all uglified/minified, but basically:

**requestmanager.js?a047:58**
/**
 * Should be used to synchronously send request
 *
 * @method send
 * @param {Object} data
 * @return {Object}
 */
```
RequestManager.prototype.send = function (data) {
    if (!this.provider) {
        console.error(errors.InvalidProvider());
        return null;
    }

    var payload = Jsonrpc.getInstance().toPayload(data.method, data.params);
    var result = this.provider.send(payload);

    if (!Jsonrpc.getInstance().isValidResponse(result)) {
        throw errors.InvalidResponse(result);
    }

    return result.result;
};
```

**property.js?4787:107**
```
Property.prototype.buildGet = function () {
    var property = this;
    return function get() {
        return property.formatOutput(property.requestManager.send({
            method: property.getter
        })); 
    };
};
```

**devtools.js**
```
    function s(t) {
        if ("test" === {
            NODE_ENV: "production"
        }.BABEL_ENV || t && t.source === window) {
            var e = t.data;
            e && "@devtools-extension" === e.source && Object.keys(g).forEach(function(t) {
                e.id && t !== e.id || ("function" == typeof g[t] ? g[t](e) : g[t].forEach(function(t) {
                    t(e)
                }))
            })
        }
    }
```

**Comment by flyswatter** [comment]
You know you can press the `{ }` button in the dev-tools and Chrome will prettify the code, for easier stack tracing???  It's great!

I'm just hoping if you do that, the `eth_mining`'s source will pop out more easily.

**Comment by vincentserpoul** [comment]
I did use the ```{ }```, without it, it was just... nonsense :).
So unfortunately, no more details than this.

I will try to do a one pager that triggers the error, so you can on your side. Not sure when I have the time though.

**Comment by flyswatter** [comment]
I'd appreciate that. Otherwise, I'm really not sure where it would come from! Very strange bug!

**Comment by flyswatter** [comment]
Let me know when you have some reproduction steps, in the meanwhile I'm closing this until we can verify this is an issue.

**Comment by lepsalex** [comment]
For what it's worth I'm getting the same error and I'm just trying to pass the new Web3 into my state:

`const browserProvider = new Web3(web3.currentProvider);`
`dispatch({type:"CONNECT" payload: browserProvider});`

Uncaught Error: The MetaMask Web3 object does not support synchronous methods like eth_mining without a callback parameter. See https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client for details.
    at MetamaskInpageProvider.send (inpage.js:246)
    at s.send (inpage.js:8230)
    at r.mining (inpage.js:8230)
    at derez (<anonymous>:2:6079)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at Object.decycle (<anonymous>:2:6109)
    at Object.e.stringify (<anonymous>:1:9197)
    at tryCatchStringify (<anonymous>:1:18852)
    at stringify (<anonymous>:1:18960)
    at toContentScript (<anonymous>:1:20255)
    at relay (<anonymous>:1:28996)
    at <anonymous>:2:114
    at invokeFunc (<anonymous>:2:24146)
    at leadingEdge (<anonymous>:2:24223)
    at debounced (<anonymous>:2:24803)
    at Object.onMessage (<anonymous>:1:30252)
    at <anonymous>:1:21010
    at Array.forEach (<anonymous>)
    at handleMessages (<anonymous>:1:20945)

**Comment by dadaphl** [comment]
Same with Vuex btw. Once you commit changes via the defined mutation the exception described earlier in the thread is raised.
```
const store = new Vuex.Store({
   ...
  mutations: {
    setTokenContract : function (state, tokenContract) {
      state.tokenContract = tokenContract
    }
   ...
```

**Comment by budaminof** [comment]
@lepsalex - we are having the same issue. did you find a solution for it?

**Comment by budaminof** [comment]
We have a react-redux application, with web3 injected into the state.
Everything is OK until we try to use the redux dev tools, then we get this error: 

Uncaught Error: The MetaMask Web3 object does not support synchronous methods like eth_mining without a callback parameter.


Any ideas?

**Comment by makoto** [comment]
@danfinlay can you reopen the case? I am also getting the same error as @budaminof when I try to dispatch an object which includes web3 instance to redux store.

I try to replicate the condition forking off truffle's react-box.
Commenting out https://github.com/makoto/react-box/blob/jest-with-redux/src/actions/actions.js#L44 will disappear the error message. Also, the error does not happen if I load the page without Metamask (via incognito mode).

**Comment by SilentCicero** [comment]
This means you are probably using a synchronous method somewhere in your code like web3.eth.accounts(). Check for any use of non-promise sync methods in your code. And for further development, never use sync methods. Always async promises or callbacks.

**Comment by makoto** [comment]
@SilentCicero I think a few people in this threads (including myself) mentioned that it's raising errors without calling any web3 functions. All I am doing is just passing the web3 object to redux store.

**Comment by SilentCicero** [comment]
@makoto oh whoops! Missed that, okay so then something is trying to call those sync methods.

I would assume either Truffle/Web3 somewhere is attempting to use a sync method, perhaps in the constructor of Web3. Otherwise something is accidentally triggering that error, under false pretense.

Can you post your web3 version, truffle (if any), and more context code/errors/traces if any?

**Comment by makoto** [comment]
@SilentCicero thanks for the help. 
This is the version I am currently having the problem with.

https://github.com/makoto/react-box/blob/jest-with-redux/src/actions/actions.js#L44

It's the fork of the latest truffle react-box.
I am in the middle of trying to add redux and jest testing to it (I am still new to redux so some of the usage may be wrong).

**Comment by SilentCicero** [comment]
If you crazy, wrap the provider object in a custom provider object. Then
trace all RPC traffic and you can see where or at least what sync call
something is trying to make ;)

**Comment by makoto** [comment]
I am currently testing against testrpc so I just checked the log and found this `net_version`.

```
  develop:testrpc net_version +3s
```

However, I can't find any code calling  `net_version`, which is very strang.

**Comment by SilentCicero** [comment]
Yes, I remember it randomly calling this. However, I believe MetaMask
overrides this so this shouldn't be the problem.

**Comment by makoto** [comment]
I worked around by not passing web3 object via redux but still feels strange...

**Comment by danfinlay** [comment]
It could be that a redux store should be text serializable, and maybe redux does something thay prevents including web3 in it.

**Comment by rongierlach** [comment]
Running into the same issue over here. Using Ethjs as my convenience lib if that helps w/ the debug.

**Comment by danfinlay** [comment]
For people arriving here: This is not where the MetaMask team tracks issues. You're looking for MetaMask/metamask-extension

If you'd like us to try to debug this for you, please create a reproduction site and submit it over there.

Closing so people don't get the wrong idea that this is where we follow up on things.
