### ISSUE TITLE
Is there a way to make 2 accounts visible to browser?

### ISSUE THREAD

**Issue by yaronvel** [MetaMask/hello#30]
Is it possible to get more than one account from web3.eth.getAccounts?

**Comment by flyswatter** [comment]
There is not currently, but if you have a good use case, we could explore UX options for this.

- Dan

**Comment by yaronvel** [comment]
I want to use it for Decentralized Ether Mixer.
See:
https://github.com/yaronvel/smart_contracts/tree/master/mixer

It would be great if the webpage would have access to all the accounts and could guide the user on his next steps.

**Comment by flyswatter** [comment]
This is a bit more advanced than the features we're focused on right now, so it's not an active priority, but if this garners enough user support, we could eventually look closer at how it should be done.
