### ISSUE TITLE
Problems on etherdelta.io

### ISSUE THREAD

**Issue by haiqu** [MetaMask/hello#32]
I've been having issues withdrawing both ETH and PLU via MetaMask on the etherdelta.github.io site. Have debugged some with the mod there (frenchhoudini) and he is of the opinion that the problem is in MetaMask.

There are two issues, one of which is a result of the other. First the withdraw fails. Second, the failure allows me to reach a place where - if I choose a specific button - the site data is corrupted and requires a reset of the site.

I'll step through the actions necessary to recreate both errors.

1. Set up an account by using Import Account in the dropbox.
2. Send some ETH to the site's wallet.
3. Do some trading. The current state of account can be seen at http://imgur.com/a/p2lJd
4. Attempt to withdraw. At this point the popup generated by MetaMask tells me that there are no funds in the address and that withdrawal is not possible. Snapshot http://imgur.com/a/GIPkl

The second error happens when I reject the trade. At that stage a second popup asks whether I want to conform the transaction. If I do the account is munged and needs resetting. I believe this second popup is unnecessary anyhow so that's an error in the program logic; if I reject the trade, I should never be able to confirm it.

**Comment by haiqu** [comment]
Title error. Closing, replace with #33

**Comment by flyswatter** [comment]
In the future we're also happy to save you time by editing titles to be more helpful to us, which we do anyways.

- Dan

**Comment by haiqu** [comment]
Actually I realized after closing it that the title could be edited. D'oh!
