### ISSUE TITLE
Problems on etherdelta.github.io

### ISSUE THREAD

**Issue by haiqu** [MetaMask/hello#33]
I've been having issues withdrawing both ETH and PLU via MetaMask on the etherdelta.github.io site. Have debugged some with the mod there (frenchhoudini) and he is of the opinion that the problem is in MetaMask.

There are two issues, one of which is a result of the other. First the withdraw fails. Second, the failure allows me to reach a place where - if I choose a specific button - the site data is corrupted and requires a reset of the site.

I'll step through the actions necessary to recreate both errors.

1. Set up an account by using Import Account in the dropbox.
2. Send some ETH to the site's wallet.
3. Do some trading. The current state of account can be seen at http://imgur.com/a/p2lJd
4. Attempt to withdraw. At this point the popup generated by MetaMask tells me that there are no funds in the address and that withdrawal is not possible. Snapshot http://imgur.com/a/GIPkl

The second error happens when I reject the trade. At that stage a second popup asks whether I want to confirm the transaction. If I do the account is munged and needs resetting. I believe this second popup is unnecessary anyhow so that's an error in the program logic; if I reject the trade, I should never be able to confirm it.

**Comment by haiqu** [comment]
Additional data: Tonight I did manage to withdraw residual ETH from EtherDelta and I had to do it in a way that suggests an error with their site after all.

In the dropbox my account is shown in two ways: Original (upper and lower case) and Modified (all lower case). I had been selecting what I though was the correct account - Original - and the withdraw was failing. Tonight I tried the Modified account number and managed to successfully withdraw my remaining ETH.

I still don't have a way of withdrawing PLU from there, and unsure if MetaMask even handles tokens yet anyhow. Perhaps someone could enlighten me on that point.

**Comment by flyswatter** [comment]
MetaMask is currently unaware of tokens, but this does not limit its ability to let you use them.

Tokens are just a type of contract, and MM lets you sign whatever tx you want.

- Dan

**Comment by haiqu** [comment]
I can view token balances at Etherscan so it's not urgent. I just have to remember that one address contains PLU so not to delete it or let it fall into disuse. :)

etherdelta mod tells me the reason for the second - all lowercase - account is due to MetaMask only being able to import from a lowercase address i.e. it doesn't use checksum. And that they accounts are equivalent. This is all news to me, but from my research it seems legit.

I am now able to use the account as expected as long as I'm careful to select the correct account i.e. all lowercase.

**Comment by haiqu** [comment]
Once final issue: how do I completely delete an account from MetaMask?

**Comment by flyswatter** [comment]
Hi @haiqu:

First of all, we just submitted a big bug fix, ever since the Geth attacks began, we switched our backend to parity, but MetaMask wasn't fully Parity compliant.  We've just closed what I hope are the final major incompatibilities, so I'd appreciate if you could re-verify if this problem is persisting.

As MetaMask currently stands, it's always deriving accounts from your original vault seed words. There isn't really such a thing as deleting, and even "creating" is actually just about deriving additional accounts.

If you don't want to use an account anymore, you could either create an entirely new vault, (you can press `back` from the lock screen), or just label the account "Do not use" or something, and just skip over it.

We're going to have more robust account management in the future, but for now, this is it.

**Comment by haiqu** [comment]
Yeah, that seems better, I'm no longer seeing the uppercase characters at all. Unfortunately he also changed the website yesterday so the result is a bit inconclusive. :/

Further issues:

1. USD is the default setting, even if it's changed this isn't sticky.
2. Build fails due to missing eth-store in Windows 7. I have the correct versions of the tools and followed the instructions to the letter but I get a failure due to secp256k1 crashing on rebuild. It has been reported to their devs but a workaround is to use `npm rebuild` and continue. The final build is also missing two files, `background.js and background.js.map` which I've been swiping from the plugin installed from the Google store.

**Comment by kumavis** [comment]
Addressing your issues individually:

https://github.com/MetaMask/metamask-plugin/issues/705
https://github.com/MetaMask/metamask-plugin/issues/706
https://github.com/MetaMask/metamask-plugin/issues/707

Please open another issue if there is something not captured.

**Comment by haiqu** [comment]
Awesome, I've reviewed those and it captures them perfectly.

Many thanks.

- Rob
