### ISSUE TITLE
eth_call block.blockhash(n) == sendTransaction block.blockhash(n+1)

### ISSUE THREAD

**Issue by wighawag** [MetaMask/hello#34]
Hi 
I think there is an issue with metamask in regard to blockhash and call
I posted the following issue on solidity as I thought it could have been a solidity issue but it turns out it works using browser solidity vm : https://github.com/ethereum/solidity/issues/1305
using metamask it fails
This must have been a issue created in the last month as I was relying on the blockhash before.

Thanks

**Comment by kumavis** [comment]
`eth_call` is just passed on to the rpc endpoint, we don't handle it specially.
what are you using as your backend?  The default is Infura, which is usually Parity.

My guess is that this is a Parity issue. Infura started using Parity during the devcon2 DoS attacks.

**Comment by wighawag** [comment]
I ll have a look at parity and post an issue there if/when I can confirm it. In the meantime, metamask is affected and this is quite a serious issue. Any chance to reopen ? 
A potential solution would be to use geth until parity is fixed. thanks

**Comment by flyswatter** [comment]
This isn't a problem with Parity, it's a problem with our load-balanced backend (Infura), which is sometimes dropping transactions.

They are actively working on adding tooling to help diagnose the issue.

In the meanwhile, the workaround is to simply run a local node and point at it.

I agree this is very serious, and so does Infura.  I'll reopen for now, but my hope is to hook you into their progress, since this is almost definitely something that needs to be addressed on their end.

**Comment by flyswatter** [comment]
Infura will be tracking progress on this issue here:
https://github.com/INFURA/infura/issues/5

**Comment by wighawag** [comment]
Ok, I am not sure the drop of tx would cause the issue mentioned here. I think it might well be a bug in parity. I am investigating now and let you know. Thanks

**Comment by wighawag** [comment]
Created an issue for parity : https://github.com/ethcore/parity/issues/3035

Tested on both geth and parity and only parity has this issue

**Comment by wighawag** [comment]
The issue https://github.com/ethcore/parity/issues/3035 has been fixed on parity.

**Comment by flyswatter** [comment]
Amazing. Great work!

**Comment by wighawag** [comment]
I just reported :)

I see that the issue is closed. Does that mean that metamask's infura is pointing to the latest version of parity (that include the fix ?) Tried it quickly but still got the same issue

**Comment by flyswatter** [comment]
No, sorry, I just figured the solution is in the pipeline, so no sense in us holding it open, but I'll leave it open until the fix is deployed.

**Comment by kumavis** [comment]
was merged into parity stable release 👍

**Comment by wighawag** [comment]
Great, Just need to wait for infura to use the latest then.
