### ISSUE TITLE
Track dependency changes in a changelog

### ISSUE THREAD

**Issue by wighawag** [MetaMask/hello#35]
Hi,
It would be cool to be able to download previous builds.
This could help when there is issue with the current build. This would help identify which build start having the issue if any

To help this further, the changelog could mention changes of dependencies if any (change of version...)

**Comment by flyswatter** [comment]
Like this?

https://github.com/MetaMask/metamask-plugin/releases

We'll look into dependency change tracking, and we'll track that on this issue.  We might just log `npm ls` results to a dependency changelog that we diff on build.

**Comment by wighawag** [comment]
Cool, should have look a bit more. thanks

**Comment by kumavis** [comment]
can also do something like `git diff 2.14.1 v3.0.1 -- package.json`
