### ISSUE TITLE
Has anything changed in how Metamask handles getEstimate method?

### ISSUE THREAD

**Issue by Manidos** [MetaMask/hello#38]
Earlier when I called `contract.myMethod.getEstimate(callback)` and the contract method threw an error, I got:

`console.log(error, result); //undefined  , ~4700000`

Now I get:

`console.log(error, result); //Error, undefined `
> Transaction execution error:
>     at d (https://localhost:3000/vendor.396f3dc5572e7a813045.bundle.js:1875:1654)
>     at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:27885)
>     at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:26989
>     at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:179:7
>     at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6682:5
>     at t.invokeTask (https://localhost:3000/vendor.396f3dc5572e7a813045.bundle.js:1875:7626)
>     at e.runTask (https://localhost:3000/vendor.396f3dc5572e7a813045.bundle.js:1875:4428)
>     at invoke (https://localhost:3000/vendor.396f3dc5572e7a813045.bundle.js:1875:8766)
>     at n.args.(anonymous function) (https://localhost:3000/vendor.396f3dc5572e7a813045.bundle.js:1854:85)

Is it how it's going to be from now or nothing has changed and there's something wrong on my side?

Thank you, Metamask team! You're truly awesome!

**Comment by flyswatter** [comment]
We did a few things to both improve gas estimations and improve error handling, so this is indeed our end.

It looks like better behavior to me, so if you agree, rest assured the change was deliberate.

**Comment by Manidos** [comment]
@flyswatter, whew, I thought it was something I messed up. Yeah, it's much better this way. Great work as always!

**Comment by kumavis** [comment]
let us know if you encounter any issues with this
