### ISSUE TITLE
Error: Unknown address - unable to sign transaction for this address

### ISSUE THREAD

**Issue by luandt-cardano** [MetaMask/hello#39]
I wrote a contract using 1st account. But when I called a function using 2nd account, it raised this error.
So, I wonder whether Metamask currently supports using 2 accounts for interact with a contract.

Thank you.

**Comment by flyswatter** [comment]
MetaMask only supports signing transactions from *the currently selected account*.

As a dapp developer, your app should check `web3.eth.accounts[0]` for its value.
- if `undefined`, the user is logged out.
- if defined, this is the only account you can currently use for that user.

If you want to experiment in development with multiple accounts, you currently must switch your metamask account by using the `switch account` button in the top right of the metamask popup.

**Comment by luandt-cardano** [comment]
Hi flyswatter,
Thank you for your response. What you are mentioning is my question.
I tested metamask with Remix in testrpc network. First, I called function f using account 1. After that, I switch to account 2 and execute function f again. This error occured.

**Comment by flyswatter** [comment]
Could you open your console and confirm that the web3 accounts array is updating?

**Comment by luandt-cardano** [comment]
I do not use accounts generated by web3 to interact with contract. I create 2 accounts in metamask,then send 10 ETH to each one from web3.eth.accounts[0].

**Comment by flyswatter** [comment]
I think you may have misunderstood me:

I'm curious if maybe metamask isn't switching the site's current account correctly, or maybe browser-solidity doesn't detect when the account has changed.

If this is the case, browser-solidity may be trying to publish with your *first* account, even though you switched to your *second* account, which would throw this error.

**Comment by flyswatter** [comment]
I have confirmed that browser-solidity does not re-check when an account has changed.

**Comment by flyswatter** [comment]
I've opened an issue on Remix there:
https://github.com/ethereum/browser-solidity/issues/482

**Comment by luandt-cardano** [comment]
thank you. I've understood this issue.
