### ISSUE TITLE
Do events fire consistently?

### ISSUE THREAD

**Issue by Manidos** [MetaMask/hello#40]
Hey! Thank you for such a great work! Metamask is the best! Have you guys noticed any skipped events? I sometimes don't get events when they are supposed to fire. Will they ever be consistent? Or is it something that can't be fixed?

**Comment by kumavis** [comment]
Heyo/ sounds like [this issue](https://github.com/MetaMask/metamask-plugin/issues/1043). I'll be taking it up today.
