### ISSUE TITLE
Detecting address change. Is there an alternative to polling?

### ISSUE THREAD

**Issue by Manidos** [MetaMask/hello#41]
Hey! I'm wondering is there a way to access Metamask events from inside an app? 

Thank you for the amazing job you're doing. You're awesome!

**Comment by flyswatter** [comment]
Do you mean like Ethereum `Events`?  Or do you mean some kind of MetaMask-specific events, like when a user changes their account or network?

We support the same web3 events API as every other web3 provider, but we don't currently provide any additional APIs, although we'd love to add some event listener API for when users and networks change.

**Comment by Manidos** [comment]
I'm sorry for not explaining my question well enough. I meant MeteMask-specific events, like when a user changes their account or network.  Thank you!

**Comment by flyswatter** [comment]
There is not yet, but we want to support such a method in the future.  Sorry about that, but I encourage you to get involved in the provider-standard evolution!

https://github.com/ethereum/interfaces/issues/16

**Comment by flyswatter** [comment]
Btw @Manidos I don't know how you still have this URL for new issues, but we usually prefer them at MetaMask/metamask-plugin.

**Comment by frozeman** [comment]
If we add the subscriptions, we could add any customs ones, but this makes it hard for dapp developers to develop cross platform. We don't want to end up in the IE mess like we had in the web 1.0 :)

**Comment by madvas** [comment]
Having to poll MetaMask every xy seconds is not preventing this mess either. I suggest you to add event to detect address change, because every decent dapp implements this polling anyway, and it just hurts every dapp's performance.
