### ISSUE TITLE
Problems to withdraw from etherdelta.github.io

### ISSUE THREAD

**Issue by RoyalCurrencyTrade** [MetaMask/hello#42]
Hi All,

trying to withdraw ETH from etherdelta I get the following error message:

You tried to send an Ethereum transaction but there was an error. Make sure you have enough ETH in your wallet to cover the gas cost (Ethereum network fee). EtherDelta sends 0.005 ETH with each transaction. This is an overestimate and the excess will get refunded to you. It's a good idea to send more than 0.005 so you can pay for not only this transaction, but also future transactions you do on EtherDelta. The gas has to come directly from your Wallet (EtherDelta has no physical way of paying gas from your deposited ETH).

of course in my account I've much more than what I'm trying to withdraw

can you please help me?

thanks

**Comment by flyswatter** [comment]
This is probably a better question for EtherDelta.

It's possible we could help if you posted a transaction hash or etherscan link. You can get one like this:
1. Open MetaMask
2. In your "History", find the transaction that failed (it should have a red icon next to it).
3. Click the transaction
4. Send us that etherscan link.

**Comment by RoyalCurrencyTrade** [comment]
I'm sorry but I'm not much expert on this, I installed MetaMask now but I can see I'v only 1 eth in my ropsten account but 0 in my prod account.

On EtherDelta I can see I've more than 2 eth (which I traded from other coin) but I can't move those on my wallet

**Comment by flyswatter** [comment]
Ah, on EtherDelta, you have to deposit ether for trading, and then when you're done, you have to withdraw that ether back to your wallet.

I think @zackcoburn could point you in the right direction.

**Comment by zackcoburn** [comment]
@flyswatter is correct. Your 2 ETH is, I assume, in the "EtherDelta" column, which means it's deposited to EtherDelta. You can use the "Withdraw" tab on EtherDelta to withdraw it from "EtherDelta" back to your "Wallet."

@RoyalCurrencyTrade, come to https://gitter.im/etherdelta/etherdelta.github.io if you still need help.

**Comment by flyswatter** [comment]
Thanks, Zack!  Closing for now.
