### ISSUE TITLE
web3 compatibility issue

### ISSUE THREAD

**Issue by imosdevteam** [MetaMask/hello#43]
A question from regarding this info from your web3 compatibility guide: 

> The user does not have the full blockchain on their machine, so data lookups can be a little slow. For this reason, we are unable to support most synchronous methods. The exceptions to this are....

Can you guys please elaborate on this for a bit? I believe that this information is important for daap devs. Are you supporting the full web3 API or a subset of it? If a subset - what methods are not supported? As for my use-case - I'm involved in building a non-trivial dapp that needs to track the blockchain for the number of confirmations after a locally executed transaction was initially confirmed on a block, to ensure that it is still on the chain after n blocks. Using web3 with a local rpc running, I can poll the blockchain (say every 20 secs) for the latest block number using `web3.eth.getBlock('latest',false);` and check if a locally executed transaction is still valid on the blockchain n blocks after the block number that it was mined on using `web3.eth.getTransactionReceipt()` - I believe this is a correct pattern but I may be wrong but regardless more accurate docs regarding which web3 methods are not supported will be very helpful. 

To clarify - for web3 methods such as getBlock() do I need to use the async version (with the callback)? And does MetaMask support all async web3 methods?

Thanks!

**Comment by flyswatter** [comment]
I can describe in more detail later if you need, but it is simple:

All web3 methods come in two forms: a synchronous and an asynchronous form. The difference is that you pass a callback function as the last argument to a web3 method to make it async.

All block tracking methods are supported, you should have no problems.

**Comment by flyswatter** [comment]
The full list of supported methods comes from provider engine:

https://github.com/MetaMask/provider-engine/blob/master/README.md#current-rpc-method-support

**Comment by imosdevteam** [comment]
Got it, makes sense. thank you.
