### ISSUE TITLE
Deposited ETH onto Etherdelta but can't do anything

### ISSUE THREAD

**Issue by francol10** [MetaMask/hello#44]
Hello,

I just deposited 10.999 ETH onto Etherdelta via Metamask. I can see the Etherdelta showing I have 10.999. However I cannot deposit anything into my wallet. I've tried 10 and even 1ETH but it keep saying "you cannot deposit more ETher than you have".

I cannot seem to even withdraw the funds.

Can you please help?

**Comment by kumavis** [comment]
Sorry we dont know about Etherdelta, please ask them for support.
I think they have a gitter chat room
