### ISSUE TITLE
Metamask bug

### ISSUE THREAD

**Issue by highyield10** [MetaMask/hello#45]
Metamask worked fine for me for EtherDelta, but now it seems to be buggy, i can`t withdraw from ED , trade or cancell orders with it, for evry transaction that I generate it says "Sorry, We are unable to locate the Transaction entry" on Etherscan, please fix this asap so we can work with it!

Thanks in advance!

**Comment by danfinlay** [comment]
This doesn't seem to be a widespread issue, may people are using ED with no problems, so please open an issue on support.metamask.io so we can give you some personal debugging time, to figure out what's wrong. We will probably need you to provide state logs:

https://support.metamask.io/kb/article/15-copying-state-logs
