### ISSUE TITLE
Colors for Metamask?

### ISSUE THREAD

**Issue by QzSG** [MetaMask/hello#46]
Sorry if this has been asked to death, I wanted to make an app showing off Metamask myriad of possible uses and wanted to theme it according to the official colors. I know its Orange but is there a color that is used without doubt? Like hex code or something, primary, secondary colors etc   ❤️

**Comment by SilentCicero** [comment]
Just eye drop a screenshot in Photoshop or Gimp. I believe there are a few special shades of orange they like to use across their UI (but I think the gang is on Holidays!)

**Comment by Zanibas** [comment]
@cjeria

**Comment by cjeria** [comment]
@QzSG Here are all hex values we use on the MetaMask fox with the primary being `#F6851B`

![metamask-fox](https://user-images.githubusercontent.com/597770/35017350-5640c764-fad1-11e7-837a-656e3e441c9b.png)
