### ISSUE TITLE
Homepage - Firefox Addon

### ISSUE THREAD

**Issue by ShalokShalom** [MetaMask/hello#48]
The page states "We’re initially building MetaMask as a Chrome extension, but eventually plan to support Firefox and beyond."

Above that, there is a link to the Firefox Addon. 
Plus, when you scroll appears the Chrome Addon in my Firefox:

![screenshot_20180104_110953](https://user-images.githubusercontent.com/6344099/34558842-e9f0fd80-f13f-11e7-972b-3387f1293e5e.png)

**Comment by danfinlay** [comment]
Fixed.

**Comment by ShalokShalom** [comment]
Thanks
