### ISSUE TITLE
Usability of uncommitted transactions

### ISSUE THREAD

**Issue by farlenkov** [MetaMask/hello#49]
If in my Dapp I call MyContract.MyFunc(xyz, function(error, result){  });  User will see a MetaMask popup. My my code will get response only if user press SUBMIT or REJECT. But if user close this popup and refresh page my code will never know status of this transaction although user still can open MetaMask and submit this transaction.

I need to show my users all of their transactions. Is there any way to get unsubmited transactions from MetaMask? Or better to automatically REJECT transaction on popup window close?

PS. This uncommitted transactions leads to terrible user experience: if user has one or more of those uncommitted transactions and click on some "buy" button in the dapp, then in MetaMask window user will see not this exact transaction request, but the oldest one from the list of uncommitted transactions. 

This oldest transaction may have different value or (in worst case) same value. User can submit this oldest transaction while thinking that it is the latest one. And as result user will don't understand what is going on and why.

**Comment by danfinlay** [comment]
Short term solution:
- Reject tx on tx window close.

Longer term solution:
- API for tracking txs, even before approval.  I remember Parity suggested an API like that in an EIP, would help if someone could find that and link it here.

**Comment by tmashuang** [comment]
Closing in favor https://github.com/MetaMask/metamask-extension/issues/3124.
